region = "supabase"

[rpc]
rpc_secret = "random_secret_12345"
rpc_addr = "[::]:8080"

[api]
api_addr = "[::]:3000"
api_domain = "example.com"

[internal_db]
manager = "sqlite"
uri = "./database/internal.db"

[orchestrator]
# Type d'orchestrateur: "docker" ou "kubernetes"
type = "docker"

# Configuration Docker/Podman
docker_host = "unix:///mnt/wsl/podman-sockets/podman-machine-default/podman-root.sock"
# Autres exemples:
# Docker standard: "unix:///var/run/docker.sock"
# Podman rootless: "unix:///run/user/1000/podman/podman.sock"
# Podman root: "unix:///run/podman/podman.sock"
# Hôte distant: "tcp://remote-host:2375"

# Configuration Kubernetes (si type = "kubernetes")
# kube_api = "https://kubernetes.default.svc"
# kube_token = "your-kubernetes-api-token"
# namespace = "sovrabase-databases"

[cluster]
node_id = "node-01"
is_rpc_server = true
rpc_servers = ["[::]:8080"]
