region = "supabase"

[rpc]
rpc_secret = "random_secret_12345"
rpc_addr = "[::]:8080"

[api]
api_addr = "[::]:3000"
api_domain = "example.com"

[internal_db]
manager = "sqlite"
uri = "./database/internal.db"

[external_db]
manager = "postgres"
uri = "postgres://root:password@localhost:5432/"

[cluster]
node_id = "node-01"
is_rpc_server = true
rpc_servers = ["[::]:8080"]
