name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: docker
    container:
      image: docker:dind
      options: --privileged
    steps:
      - name: Checkout code
        run: |
          apk add --no-cache git
          git clone --depth 1 --branch ${GITHUB_REF_NAME} https://oauth2:${GITHUB_TOKEN}@${GITHUB_SERVER_URL#https://}/${GITHUB_REPOSITORY}.git .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Start Docker daemon
        run: |
          dockerd &
          sleep 5

      - name: Login to Forgejo Container Registry
        if: github.event_name != 'pull_request'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REPO_URL }} -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ env.REPO_URL }}/${{ github.repository }}:latest \
                       -t ${{ env.REPO_URL }}/${{ github.repository }}:${{ github.sha }} .

      - name: Push Docker image
        if: github.event_name != 'pull_request'
        run: |
          docker push ${{ env.REPO_URL }}/${{ github.repository }}:latest
          docker push ${{ env.REPO_URL }}/${{ github.repository }}:${{ github.sha }}
