name: Hello World

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  hello:
    runs-on: docker
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: list directory contents
        run: ls -la
