// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/sovrabase.proto

package sovrabase

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForwardCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	TargetNode    string                 `protobuf:"bytes,2,opt,name=target_node,json=targetNode,proto3" json:"target_node,omitempty"`
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardCommandRequest) Reset() {
	*x = ForwardCommandRequest{}
	mi := &file_proto_sovrabase_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardCommandRequest) ProtoMessage() {}

func (x *ForwardCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sovrabase_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardCommandRequest.ProtoReflect.Descriptor instead.
func (*ForwardCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_sovrabase_proto_rawDescGZIP(), []int{0}
}

func (x *ForwardCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ForwardCommandRequest) GetTargetNode() string {
	if x != nil {
		return x.TargetNode
	}
	return ""
}

func (x *ForwardCommandRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type ForwardCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardCommandResponse) Reset() {
	*x = ForwardCommandResponse{}
	mi := &file_proto_sovrabase_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardCommandResponse) ProtoMessage() {}

func (x *ForwardCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sovrabase_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardCommandResponse.ProtoReflect.Descriptor instead.
func (*ForwardCommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_sovrabase_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForwardCommandResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ForwardCommandResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_sovrabase_proto protoreflect.FileDescriptor

const file_proto_sovrabase_proto_rawDesc = "" +
	"\n" +
	"\x15proto/sovrabase.proto\x12\tsovrabase\"\xd3\x01\n" +
	"\x15ForwardCommandRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x1f\n" +
	"\vtarget_node\x18\x02 \x01(\tR\n" +
	"targetNode\x12D\n" +
	"\x06params\x18\x03 \x03(\v2,.sovrabase.ForwardCommandRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\x16ForwardCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2n\n" +
	"\x15ForwardCommandService\x12U\n" +
	"\x0eForwardCommand\x12 .sovrabase.ForwardCommandRequest\x1a!.sovrabase.ForwardCommandResponseB\"Z github.com/ketsuna-org/sovrabaseb\x06proto3"

var (
	file_proto_sovrabase_proto_rawDescOnce sync.Once
	file_proto_sovrabase_proto_rawDescData []byte
)

func file_proto_sovrabase_proto_rawDescGZIP() []byte {
	file_proto_sovrabase_proto_rawDescOnce.Do(func() {
		file_proto_sovrabase_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sovrabase_proto_rawDesc), len(file_proto_sovrabase_proto_rawDesc)))
	})
	return file_proto_sovrabase_proto_rawDescData
}

var file_proto_sovrabase_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_sovrabase_proto_goTypes = []any{
	(*ForwardCommandRequest)(nil),  // 0: sovrabase.ForwardCommandRequest
	(*ForwardCommandResponse)(nil), // 1: sovrabase.ForwardCommandResponse
	nil,                            // 2: sovrabase.ForwardCommandRequest.ParamsEntry
}
var file_proto_sovrabase_proto_depIdxs = []int32{
	2, // 0: sovrabase.ForwardCommandRequest.params:type_name -> sovrabase.ForwardCommandRequest.ParamsEntry
	0, // 1: sovrabase.ForwardCommandService.ForwardCommand:input_type -> sovrabase.ForwardCommandRequest
	1, // 2: sovrabase.ForwardCommandService.ForwardCommand:output_type -> sovrabase.ForwardCommandResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_sovrabase_proto_init() }
func file_proto_sovrabase_proto_init() {
	if File_proto_sovrabase_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sovrabase_proto_rawDesc), len(file_proto_sovrabase_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sovrabase_proto_goTypes,
		DependencyIndexes: file_proto_sovrabase_proto_depIdxs,
		MessageInfos:      file_proto_sovrabase_proto_msgTypes,
	}.Build()
	File_proto_sovrabase_proto = out.File
	file_proto_sovrabase_proto_goTypes = nil
	file_proto_sovrabase_proto_depIdxs = nil
}
