// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/sovrabase.proto

package sovrabase

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ForwardCommandService_ForwardCommand_FullMethodName = "/sovrabase.ForwardCommandService/ForwardCommand"
)

// ForwardCommandServiceClient is the client API for ForwardCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ForwardCommand service
type ForwardCommandServiceClient interface {
	ForwardCommand(ctx context.Context, in *ForwardCommandRequest, opts ...grpc.CallOption) (*ForwardCommandResponse, error)
}

type forwardCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewForwardCommandServiceClient(cc grpc.ClientConnInterface) ForwardCommandServiceClient {
	return &forwardCommandServiceClient{cc}
}

func (c *forwardCommandServiceClient) ForwardCommand(ctx context.Context, in *ForwardCommandRequest, opts ...grpc.CallOption) (*ForwardCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardCommandResponse)
	err := c.cc.Invoke(ctx, ForwardCommandService_ForwardCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForwardCommandServiceServer is the server API for ForwardCommandService service.
// All implementations must embed UnimplementedForwardCommandServiceServer
// for forward compatibility.
//
// ForwardCommand service
type ForwardCommandServiceServer interface {
	ForwardCommand(context.Context, *ForwardCommandRequest) (*ForwardCommandResponse, error)
	mustEmbedUnimplementedForwardCommandServiceServer()
}

// UnimplementedForwardCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForwardCommandServiceServer struct{}

func (UnimplementedForwardCommandServiceServer) ForwardCommand(context.Context, *ForwardCommandRequest) (*ForwardCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardCommand not implemented")
}
func (UnimplementedForwardCommandServiceServer) mustEmbedUnimplementedForwardCommandServiceServer() {}
func (UnimplementedForwardCommandServiceServer) testEmbeddedByValue()                               {}

// UnsafeForwardCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForwardCommandServiceServer will
// result in compilation errors.
type UnsafeForwardCommandServiceServer interface {
	mustEmbedUnimplementedForwardCommandServiceServer()
}

func RegisterForwardCommandServiceServer(s grpc.ServiceRegistrar, srv ForwardCommandServiceServer) {
	// If the following call pancis, it indicates UnimplementedForwardCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ForwardCommandService_ServiceDesc, srv)
}

func _ForwardCommandService_ForwardCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardCommandServiceServer).ForwardCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardCommandService_ForwardCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardCommandServiceServer).ForwardCommand(ctx, req.(*ForwardCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ForwardCommandService_ServiceDesc is the grpc.ServiceDesc for ForwardCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForwardCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sovrabase.ForwardCommandService",
	HandlerType: (*ForwardCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ForwardCommand",
			Handler:    _ForwardCommandService_ForwardCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sovrabase.proto",
}
